stages:
  - test

hardhat-test:
  stage: test
  image: registry.gotbitgames.co:444/yarn-firebase
  tags:
    - k8s
  variables:
    MORALIS_ID: $MORALIS_ID_DEV
  script:
    - cd contracts
    - yarn test:cicd
